#!/usr/bin/env bash
date='2000-01-01T00:00:00+0000'
email=''
name='a'
export GIT_AUTHOR_DATE="$date"
export GIT_AUTHOR_EMAIL="$email"
export GIT_AUTHOR_NAME="$name"
export GIT_COMMITTER_DATE="$date"
export GIT_COMMITTER_EMAIL="$email"
export GIT_COMMITTER_NAME="$name"
git add .
git commit -m 0 "$@"
